README.md, benchviewer/static/files/algo_level.txt, benchviewer/templates/benchmark_description.html, benchviewer/templates/description.html, benchviewer/templates/index.html
=> Changed algorithm level to algorithmic level

benchviewer/main.py, benchviewer/src/backend.py
Instead of generating the whole zip file first, start streaming immediately.
=> Stream zip file immediately

.github/workflows/server_deployment.yml, benchviewer/README.md, benchviewer/templates/index.html
- removed hint for timeout
- added the config.json to the rsync because it is needed for #num benchmarks calculation for algo level
=> Server sync adaptions

mqt/bench/benchmark_generator.py, mqt/bench/utils/utils.py, setup.py
Pull request for:
Issues #55 and #49
=> Transpile calls

mqt/bench/tests/test_all.py, mqt/bench/utils/utils.py, setup.py
PR for issue #25: Removed manually created coupling map and use Fake Washington Backend instead
=> Couplingmap ibmq washington

mqt/benchviewer/src/backend.py, setup.py
=> ✨ improved filter logic for speed-up

pyproject.toml
=> :dependabot:  Dependency management

.github/workflows/coverage.yml, .github/workflows/deploy.yml, mqt/benchviewer/src/backend.py
=> 🔧 Configure GITHUB_TOKEN API Authorization

README.md
By combining the PyPi and our webserver workflows, this shield is outdated.
=> 🔥 removed old shield from Readme

.pre-commit-config.yaml, src/mqt/bench/utils.py
So far, the Qiskit.QuantumCircuit object is not copied and was modified by the method. To avoid undesired behavior (such as the compiled circuit not having measurements anymore), the QuantumCircuit is now copied before.
=> 🐛 SupermarQ Feature Calculation

README.md
=> 💡 fixed deprecated issue in readme

.github/workflows/coverage.yml, .github/workflows/deploy.yml, pyproject.toml, src/mqt/bench/benchmark_generator.py, src/mqt/bench/evaluation/evaluation_visualization.ipynb, tests/devices/test_ibm_device_support.py, tests/devices/test_ionq_device_support.py, tests/devices/test_oqc_device_support.py, tests/devices/test_quantinuum_device_support.py, tests/devices/test_rigetti_device_support.py
necessary because of a bugfix that has been introduced in v.048.0 required for MQT Predictor
=> 📌 increased lower cap of pytket_qiskit v0.48.0 

src/mqt/bench/benchmarks/qiskit_application_finance/portfolioqaoa.py
This PR removes a duplicate round of measurements at the of the Portfolio QAOA circuits.
=> 🩹 remove duplicate round of measurements

.github/workflows/cd.yml, .github/workflows/ci.yml, noxfile.py, pyproject.toml
This PR updates the CI and CD workflows from mqt-workflows.
=> ⚗️ update mqt-workflows version

docs/conf.py, noxfile.py, pyproject.toml, uv.lock
Adjust to `mqt-workflows` v1.4.1
=> 👷 adjusted to mqt workflow update

noxfile.py
Resolves https://github.com/cda-tum/mqt-bench/issues/532
=> :white_check_mark: Test up to Python 3.13

README.md, docs/_templates/page.html
This PR updates the readme due to the new locations of the [logos](https://github.com/munich-quantum-toolkit/.github/tree/main/docs/_static).
=> 📝 Update README and resource links due to repository migration

src/mqt/bench/benchmarks/shor.py, tests/test_bench.py
Shortened and improved the generation logic for shor.
Resolves #217
=> :art: Refactored Implementation of Shor's Benchmark

.github/contributing.md, .github/release-drafter.yml, CHANGELOG.md, UPGRADING.md, docs/CHANGELOG.md, docs/UPGRADING.md, docs/index.md
This PR adds a dedicated changelog and upgrade guide to the project as a centralized place to keep track of significant updates to this library.
Both of these files are curated selections of the PRs that go into a release.
Notably, these are written for humans and not for machines.
As such, they are not automatically scraped together like the drafts created by the release drafter action. These drafts may still serve as blueprints for corresponding changelog entries.
=> :memo: Added CHANGELOG and UPGRADING information

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/contributing.md, .github/support.md, docs/conf.py, docs/development_guide.md, docs/index.md, docs/installation.md
Updated documentation to align with [MQT QCEC](https://mqt.readthedocs.io/projects/qcec/en/latest/).
=> :memo: Update Documentation

README.md, docs/_templates/page.html, docs/conf.py, docs/index.md
This PR introduces the new Readme format based on https://github.com/munich-quantum-toolkit/core/pull/953.
=> 💡 updated readme and RtDs according to new guidelines

src/mqt/bench/benchmarks/ae.py, src/mqt/bench/benchmarks/graphstate.py, src/mqt/bench/benchmarks/grover.py, src/mqt/bench/benchmarks/hhl.py, src/mqt/bench/benchmarks/qnn.py, src/mqt/bench/benchmarks/vqe_real_amp.py, src/mqt/bench/benchmarks/vqe_su2.py, src/mqt/bench/benchmarks/vqe_two_local.py
Due to the minimum Qiskit version being `v1.3.2` now, several import statements can be simplified.
=> :art: Simplify Imports

src/mqt/bench/cli.py, tests/test_cli.py
Added the `random_parameters` option to the cli.
=> :sparkles: Add random parameter option to cli

README.md, docs/index.md, docs/references.md, docs/refs.bib
This PR adds support information to the README and the documentation.
For more information, see https://github.com/munich-quantum-toolkit/.github/pull/49.
=> ❤️ Add support option

.github/workflows/ci.yml, CHANGELOG.md, UPGRADING.md
See https://github.com/munich-quantum-toolkit/core/pull/1165/ for more information.
Fixes #661
=> 🔥 Drop support for x86 macOS systems
