benchviewer/main.py, benchviewer/src/backend.py
With this PR, the zipping is done again by saving the generated zip files on storage instead of in memory only to avoid server problems if several users download all files at the same time.
=> Remove in memory zipping

mqt/bench/benchmark_generator.py, mqt/bench/tests/test_all.py, mqt/bench/utils/utils.py, setup.py
Removed functionalities (as listed in #48) for:
- printing the circuits for the created benchmarks
- simulating and saving the histogram for the created benchmarks
=> Remove histogram functions

.github/workflows/deploy.yml
The `master` branch of the `gh-action-pypi-publish` action has been deprecated in July.
This tiny PR updates the action to the recommended usage from [https://github.com/pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish).
=> 👷 update github action to publish to pypi

.git_archival.txt, .gitattributes, pyproject.toml
Following [https://scikit-hep.org/developer/packaging#versioning-mediumhigh-priority](https://scikit-hep.org/developer/packaging#versioning-mediumhigh-priority), this PR adds the necessary steps to allow git archives (including the ones generated from GitHub) to also support versioning.
This requires setuptools_scm>=7.
=> 📦 support versioning in git

mqt/bench/benchmark_generator.py, mqt/bench/utils/utils.py
It was meant to solve #95 but actually the problem was never present for the `get_one_benchmark` method since that method always returns the Qiskit::QuantumCircuit object. Nevertheless, the OQC error handling is improved:
- It is done now immediately after creation.
- The `opaque` function of OpenQASM is now used to avoid introducing non-native gates in the native and mapped levels.
=> Fix oqc qasm

.github/workflows/server_deploy.yml
👷 server deployment is only triggered after a release has been created
=> Adjusted Server Deployment

mqt/benchviewer/templates/index.html
I think the word is meant to be "rather". =)
=> Fix a typo in abstraction level selection block

mqt/bench/tests/test_all.py, mqt/bench/utils/tket_helper.py
Resolves #169.
⚡  also adds a new post-mapping, layout-preserving optimization pass for tket that should improve its results.
=> 🐛 Quick-fix for uni-directional routing with TKET

.github/workflows/server_deploy.yml
- Adjusted the deployment script, such that only one file is copied to the webserver as a trigger
- On the webserver, a daemon is scanning this files for changes
- If a change is detected, `pip install -U mqt.bench` is executed
=> 🎨 improved the webserver deployment

src/mqt/bench/benchmarks/qaoa.py
The used QAOA method from qiskit automatically adds measurements, so manually adding them is not necessary.
=> 🐛 Removed redundant measurements

.github/codecov.yml, src/mqt/bench/evaluation/evaluation.py, src/mqt/bench/utils.py, tests/test_bench.py
This PR improves the testing by increased code coverage.
=> ✅  Increase Testing Code Coverage 

src/mqt/bench/utils.py, tests/test_bench.py
I compared our implementation of the SupermarQ feature calculation with their [implementation](https://github.com/Infleqtion/client-superstaq/blob/main/supermarq-benchmarks/supermarq/converters.py) and copied their code for `liveness` and `program_communication` because it seemed better to me in terms of understadability.
=> 🎨 Improved SupermarQ feature calculation

src/mqt/benchviewer/templates/index.html
This PR links the MQT Logo to the [MQT website](https://www.cda.cit.tum.de/research/quantum/mqt/).
=> 🎨 added link to MQT website

pyproject.toml, src/mqt/bench/benchmark_generator.py, src/mqt/bench/cli.py, tests/test_cli.py
Mainly to be used automatically by tooling.
Options are simple CLI options for now, but should probably become more dynamic in the future (does argparse support dynamic/unregistered options?).
=> Add basic CLI around get_benchmark()

pyproject.toml
=> ⬇️ added temporary cap for numpy

.github/workflows/cd.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, noxfile.py, pyproject.toml, src/mqt/bench/benchmark_generator.py, src/mqt/bench/benchmarks/random.py, src/mqt/bench/devices/calibration.py, src/mqt/bench/devices/device.py, src/mqt/bench/devices/ibm.py, src/mqt/bench/devices/ionq.py, src/mqt/bench/devices/iqm.py, src/mqt/bench/devices/oqc.py, src/mqt/bench/devices/quantinuum.py, src/mqt/bench/devices/rigetti.py, src/mqt/bench/evaluation/evaluation_visualization.ipynb, tests/devices/test_devices.py, tests/devices/test_ibm_device_support.py, tests/test_bench.py, tests/test_pregenerated_zip.py
This PR
- updates the pre-commit config
- updates the CI/CD workflows
- adds python 3.13 support
=> 👷 update framework

README.md
Corrected the README example: The description of getting representing the GHZ-state used the incorrect `benchmark_name='dj'`  ('Deutsch-Jozsa'). Updated the example to use the `benchmark_name='ghz'` .
=> Corrected the readme ghz-example

src/mqt/bench/utils.py
This PR slightly adjusts the imports in the `utils.py` file so that `qiskit_optimization` is important lazily.
Besides slightly improving the general import speed, this also avoids a `docplex` syntax warning appearing on Python 3.12+ when importing `mqt.bench`.
=> ⚡🚨 make `qiskit_optimization` import lazy

src/mqt/bench/benchmark_generator.py, tests/test_cli.py
This PR addresses a bug where the provider's availability was checked, even when the level was set to ``mapped``. This caused an issue if ``provider_name`` was not provided in ``mqt.bench.cli`` while using the ``mapped`` level.
=> 🐛 Verify provider and device availability based on selected level

src/mqt/bench/devices/provider.py, src/mqt/bench/utils.py, src/mqt/bench/viewer/backend.py, tests/test_benchviewer.py
This PR removes some code that has become obsolete at the time we moved the minimum supported Python version to 3.10.
=> 🔥 removing obsolete code for importlib backwards compatibility

.dockerignore, .github/workflows/docker.yml, Dockerfile, src/mqt/bench/cli.py, tests/test_cli.py
This PR sets up an MQT Bench docker container so that the CLI can be run from a stable environment with locked dependencies.
The dockerfile is based on the excellent guide at https://hynek.me/articles/docker-uv/
The PR also introduces a new CI workflow for building and publishing the containers to Docker Hub under the `munichquantumtoolkit/mqt-bench` project.
=> 🐳 MQT Bench Docker Container

README.md, docs/index.rst, frontend/src/mqt/bench/viewer/templates/index.html
This PR fixes an outdated hyperlink to PennyLane.
=> :bug: Fix an outdated reference to PennyLane

.github/workflows/docker.yml
This PR adapts the docker CI workflow to only run the build whenever all the credentials are appropriately set.
As a consequence, it does not run on PRs from forks by default, but only if the forks set the required credentials in their repo settings.
=> 👷 only run docker build if credentials are available

frontend/pyproject.toml
This PR fixes an issue where the static files for the MQT Bench frontend would not be installed with the frontend. This would prevent the server from properly starting.
=> 🐛 fix static files not being installed with frontend

pyproject.toml
This PR makes sure to exclude a `qiskit-aer==0.16.1` since it causes the CI runner on linux arm to crash.
=> 📌 restricted qiskit-aer dependency

noxfile.py, pyproject.toml, src/mqt/bench/benchmark_generation.py, uv.lock
Resolves https://github.com/cda-tum/mqt-bench/issues/520
=> :sparkles: Re-add support for Python 3.9

pyproject.toml, src/mqt/bench/benchmark_generation.py, src/mqt/bench/devices/__init__.py, tests/test_bench.py
Extended available gatesets by `clifford+t`.
=> :sparkles: Added `clifford+t` gateset

noxfile.py, pyproject.toml, sitecustomize.py, src/mqt/bench/targets/devices/ibm.py, uv.lock
This PR speeds up the test suite by parallelizing test execution and using a lighter-weight monitor for coverage collection on Python 3.12+.
This is based on the blog post: https://blog.trailofbits.com/2025/05/01/making-pypis-test-suite-81-faster/ which is definitely worth a read.
Working that out even made me discover a small bug in our target generation logic, where the generation of the IBM device targets would not be entirely deterministic, and, hence, neither were the mapped level benchmarks mapped to IBM devices. See https://github.com/munich-quantum-toolkit/bench/pull/602/commits/4ed07f3fce0ab3f3e89b2623192fb9a79af76633.
This is a pretty easy win in terms of testing speed. On my desktop with 32-cores this reduced the test time from 32s to 9s.
=> ⚡ Speed up test suite

src/mqt/bench/benchmark_generation.py, tests/test_bench.py
The mirror circuit generation introduced in #577 did not quite work as expected on the mapped level.
This was discovered in #597 by @simon1hofmann.
Circuits would have barriers and measurements applied to _all_ of the qubits instead of only the "active" ones.
This PR addresses this shortcoming by rewriting parts of the mirror circuit generation logic. Barriers and measurements are now only added to non-idle qubits.
Tests have been adjusted to be slightly more rigorous.
=> 🐛 Fix mirror circuit generation on mapped level

.github/workflows/ci.yml, CHANGELOG.md, UPGRADING.md
This PR reverts #666, which dropped support for x86 macOS systems. This is because GitHub Actions has introduced a `macos-15-intel` runner, enabling us to test on x86 macOS until August 2027.
=> 🍎 Restore support for x86 macOS systems
